#!/bin/bash

unameOut="$(uname -s)"

echo "Running on ${unameOut} as ${USER}"

case "${unameOut}" in
    Linux*)
        echo "Installing Linux dependencies"
        sudo apt-get update -y
        sudo apt-get install -y \
            build-essential \
            cmake \
            libmp3lame-dev \
            libshout3-dev \
            libconfig++-dev \
            libfftw3-dev \
            librtlsdr-dev \
            libsoapysdr-dev \
            libpulse-dev
        ;;

    Darwin*)
        echo "Installing MacOS dependencies"

        # detect when running in github workflow and skip `brew update` (relay on fresh OS image)
        if [ -n "${GITHUB_ACTION}" ] ; then
            echo "running in GitHub Workflow, skipping brew update"
            export HOMEBREW_NO_AUTO_UPDATE=1
            export HOMEBREW_NO_INSTALL_UPGRADE=1
            export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
            echo "running ${ImageOS} vsersion ${ImageVersion}"
        else
            brew update
        fi

        brew install \
            lame \
            libshout \
            libconfig \
            fftw \
            librtlsdr \
            soapysdr \
            pulseaudio \
            pkg-config

        ;;

    *)
        echo "Error: Machine not supported"
        exit -1
esac
