#!/bin/bash -e

platform="${1}"

if [ -z "${platform}" ]; then
    echo "Error: platform not set"
    exit -1
fi

echo "running build for ${platform} on $(source /etc/os-release ; echo ${VERSION})"

case "${platform}" in
    rpi3b)
        CMAKE_ARGS="-DPLATFORM=rpiv2 -DCMAKE_BUILD_TYPE=Release -DNFM=TRUE -DBUILD_UNITTESTS=TRUE"
        ;;

    *)
        echo "Error: Platform '${platform}' not supported"
        exit -1
esac

# make a build dir
rm -rf build || true ; mkdir build
cd build

# configure and build
cmake ${CMAKE_ARGS} ../
VERBOSE=1 make -j

# run unit tests
src/unittests

# run rtl_airband to get version string and exit
src/rtl_airband -v
