FROM ubuntu:latest

RUN sed -i 's/^# \(.*export LS_OPTIONS.*$\)/\1/g' ~/.bashrc && \
    sed -i 's/^# \(.*alias ll.*$\)/\1/g' ~/.bashrc

WORKDIR /app
COPY .github/install_dependencies /app/
RUN apt-get install git sudo gdb -y
RUN /app/install_dependencies

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
