#!/bin/bash -e

cd `dirname $0`/../

# build container
docker build -t rtl_airband-dev -f .devcontainer/Dockerfile .

# run bash in container
docker run --rm -v $(pwd):/app/ -it --entrypoint bash rtl_airband-dev
