name: Run CI

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '39 13 * * *' # run daily

jobs:
  ci_build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, macos-13, ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 35 # runtime across all OSs, runs can get queued
    steps:
    - name: Runner Info
      run: printenv | sort

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0' # need full history to get version from git tag

    - name: Install packaged dependencies
      run: .github/install_dependencies

    - name: Configure
      run: |
        cmake -B ${{github.workspace}}/build_Debug -DCMAKE_BUILD_TYPE=Debug -DBUILD_UNITTESTS=TRUE
        cmake -B ${{github.workspace}}/build_Debug_NFM -DCMAKE_BUILD_TYPE=Debug -DNFM=TRUE -DBUILD_UNITTESTS=TRUE
        cmake -B ${{github.workspace}}/build_Release -DCMAKE_BUILD_TYPE=Release -DBUILD_UNITTESTS=TRUE
        cmake -B ${{github.workspace}}/build_Release_NFM -DCMAKE_BUILD_TYPE=Release -DNFM=TRUE -DBUILD_UNITTESTS=TRUE

    - name: Build
      run: |
        VERBOSE=1 cmake --build ${{github.workspace}}/build_Debug -j4
        VERBOSE=1 cmake --build ${{github.workspace}}/build_Debug_NFM -j4
        VERBOSE=1 cmake --build ${{github.workspace}}/build_Release -j4
        VERBOSE=1 cmake --build ${{github.workspace}}/build_Release_NFM -j4

    - name: Unit Tests
      run: |
        ${{github.workspace}}/build_Debug/src/unittests
        ${{github.workspace}}/build_Debug_NFM/src/unittests
        ${{github.workspace}}/build_Release/src/unittests
        ${{github.workspace}}/build_Release_NFM/src/unittests

    - name: Install
      run: sudo cmake --install ${{github.workspace}}/build_Release_NFM

    - name: Test run
      run: /usr/local/bin/rtl_airband -v
