name: Code Formatting

on:
  pull_request:
  schedule:
    - cron: '39 13 * * *' # run daily 

jobs:
  code_formatting:
    runs-on: ubuntu-latest
    steps:

    - name: Runner Info
      run: printenv | sort

    - name: Checkout
      uses: actions/checkout@v4

    - name: working dir
      run: find .

    - name: clang-format
      uses: RafikFarhad/clang-format-github-action@v3
      with:
        sources: "src/*.h,src/*.cpp"
        style: "file"
