name: Code Formatting

on:
  pull_request:
  schedule:
    - cron: '39 13 * * *' # run daily 

jobs:
  code_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: "src/*.h,src/*.cpp"
          style: "file"
