name: Code Formatting

on:
  pull_request:
  schedule:
    - cron: '39 13 * * *' # run daily

jobs:
  code_formatting:
    runs-on: ubuntu-latest
    steps:

    - name: Runner Info
      run: printenv | sort

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Clang Format
      run: sudo apt-get install clang-format-14

    - name: Run Clang Format
      run: |
        ./scripts/reformat_code
        git diff --exit-code
